[package]
name = "snake_xenzia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto=true
strip=true


[dependencies]
crossterm = "0.27.0"